require('./middlewareMocks')
require('./events/listeners')

const {publishNewUser} = require('./events/publishers')

const Users = [ 
    { fullName: 'SAGUAS ANDRE RENATO OLIVEIRA',
    userId: '00000',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00000',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00000' },
    { fullName: 'SILVA DANILO',
    userId: '00001',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00001',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00001' },
    { fullName: 'MARINS ALAN CUNHA OLIVEIRA',
    userId: '00002',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00002',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00002' },
    { fullName: 'CUNHA KATIA CLEMER',
    userId: '00003',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00003',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00003' },
    { fullName: 'FERREIRA LINO NALY',
    userId: '00004',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00004',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00004' },
    { fullName: 'DIAS STONEM APOLIDORIO',
    userId: '00005',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00005',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00005' },
    { fullName: 'ISMAEL BRASIL',
    userId: '00006',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00006',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00006' },
    { fullName: 'JOSEAN ANDRE ALEXANDRE',
    userId: '00007',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00007',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00007' },
    { fullName: 'CHAGAS THIAGO OLIVEIRA',
    userId: '00008',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00008',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00008' },
    { fullName: 'VINICIUS SANTANA CARVALHO BENSUSSAM',
    userId: '00009',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00009',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00009' },
    { fullName: 'PAULA ZANCHETA',
    userId: '00010',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00010',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00010' },
    { fullName: 'SAMUEL WAGNER',
    userId: '00011',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00011',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00011' },
    { fullName: 'PADRAO DE DONIZETI',
    userId: '00012',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00012',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00012' },
    { fullName: 'WAGNER VIANA CUNHA CRISTOFOLI',
    userId: '00013',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00013',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00013' },
    { fullName: 'OLIVEIRA ALMEIDA',
    userId: '00014',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00014',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00014' },
    { fullName: 'ARLETE CAIADO SERGIO',
    userId: '00015',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00015',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00015' },
    { fullName: 'JUNIOR RODOLFO',
    userId: '00016',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00016',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00016' },
    { fullName: 'VALENCA AUGUSTO',
    userId: '00017',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00017',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00017' },
    { fullName: 'PAULA SOUZA',
    userId: '00018',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00018',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00018' },
    { fullName: 'FRANCISCO CARVALHO FIGUEIREDO LEAL',
    userId: '00019',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00019',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00019' },
    { fullName: 'SOUZA DA SERODIO',
    userId: '00020',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00020',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00020' },
    { fullName: 'CALDAS JOSE',
    userId: '00021',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00021',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00021' },
    { fullName: 'DONIZETI ALVES',
    userId: '00022',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00022',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00022' },
    { fullName: 'MENDES FISCHER LUDMILA SOUZA',
    userId: '00023',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00023',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00023' },
    { fullName: 'HENRIQUE NADIA CAMPOS',
    userId: '00024',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00024',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00024' },
    { fullName: 'PAULA FISCHER ANTUNES',
    userId: '00025',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00025',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00025' },
    { fullName: 'AUGUSTO THIAGO LOURENCO GOMES',
    userId: '00026',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00026',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00026' },
    { fullName: 'THIAGO CAMARA ANDERSON',
    userId: '00027',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00027',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00027' },
    { fullName: 'CHRISTIANO SA',
    userId: '00028',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00028',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00028' },
    { fullName: 'DONIZETI ANDRE GUSTAVO',
    userId: '00029',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00029',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00029' },
    { fullName: 'KELLI NUNES RODOLFO',
    userId: '00030',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00030',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00030' },
    { fullName: 'SANTOS MAZZINI DIEGO',
    userId: '00031',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00031',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00031' },
    { fullName: 'DONIZETI DEYVID COSTA RENATO',
    userId: '00032',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00032',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00032' },
    { fullName: 'DOUGLAS MAURO CONY WILLYSON',
    userId: '00033',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00033',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00033' },
    { fullName: 'VIANA SOUZA',
    userId: '00034',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00034',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00034' },
    { fullName: 'WELLINGTON MENDES',
    userId: '00035',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00035',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00035' },
    { fullName: 'WIILLIAM ALISON',
    userId: '00036',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00036',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00036' },
    { fullName: 'SOUZA MENDES CARVALHO',
    userId: '00037',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00037',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00037' },
    { fullName: 'OLIVEIRA RAFAEL LUCK',
    userId: '00038',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00038',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00038' },
    { fullName: 'ALEXANDRE PEDROSO GOMES',
    userId: '00039',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00039',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00039' },
    { fullName: 'NALY PEDRO CAMILA FERNANDO',
    userId: '00040',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00040',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00040' },
    { fullName: 'AUGUSTO MARTINS CORTES',
    userId: '00041',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00041',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00041' },
    { fullName: 'ANTUNES BRUNO ANDERSON',
    userId: '00042',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00042',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00042' },
    { fullName: 'CAMPOS GIULIANI PEDROSO',
    userId: '00043',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00043',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00043' },
    { fullName: 'WESLLEY GOMES FELIPE CALDAS',
    userId: '00044',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00044',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00044' },
    { fullName: 'DIEGO ARLETE WILLYSON',
    userId: '00045',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00045',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00045' },
    { fullName: 'RAFAEL CARVALHO NETO',
    userId: '00046',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00046',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00046' },
    { fullName: 'SILVA RIBEIRO DANTAS LOURENCO',
    userId: '00047',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00047',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00047' },
    { fullName: 'WAGNER ALEXANDRE',
    userId: '00048',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00048',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00048' },
    { fullName: 'AGUILERA NALY',
    userId: '00049',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00049',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00049' },
    { fullName: 'MAZZINI APOLIDORIO',
    userId: '00050',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00050',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00050' },
    { fullName: 'VINICIUS CAMPOS',
    userId: '00051',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00051',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00051' },
    { fullName: 'BOTELHO BENSUSSAM',
    userId: '00052',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00052',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00052' },
    { fullName: 'MELLO FRANCISCO JUNIOSS TERTULIANO',
    userId: '00053',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00053',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00053' },
    { fullName: 'CUNHA SALVARANI SANTOS',
    userId: '00054',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00054',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00054' },
    { fullName: 'SENA CLEMER QUEIROZ',
    userId: '00055',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00055',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00055' },
    { fullName: 'ANTUNES COSTA TORRES',
    userId: '00056',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00056',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00056' },
    { fullName: 'FERNANDO PELIZER BENSUSSAM',
    userId: '00057',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00057',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00057' },
    { fullName: 'CHRISTIANO MARINS GUSTAVO',
    userId: '00058',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00058',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00058' },
    { fullName: 'VILAR PAULA SANTANA',
    userId: '00059',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00059',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00059' },
    { fullName: 'OLIVEIRA DIAS',
    userId: '00060',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00060',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00060' },
    { fullName: 'BRASIL PELIZER',
    userId: '00061',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00061',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00061' },
    { fullName: 'FRANCISCO VINICIUS SANTOS BAPTISTA',
    userId: '00062',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00062',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00062' },
    { fullName: 'CARLOS GOMES',
    userId: '00063',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00063',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00063' },
    { fullName: 'GALDINO DEYVID JACOBSEN',
    userId: '00064',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00064',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00064' },
    { fullName: 'NUNES LUIZ SAMUEL',
    userId: '00065',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00065',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00065' },
    { fullName: 'EDUARDO CARLETO APOLIDORIO',
    userId: '00066',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00066',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00066' },
    { fullName: 'THIAGO SENA',
    userId: '00067',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00067',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00067' },
    { fullName: 'BENSUSSAM ALMEIDA ANDRE SENA',
    userId: '00068',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00068',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00068' },
    { fullName: 'RENATO MESQUITA ALEX BOTELHO',
    userId: '00069',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00069',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00069' },
    { fullName: 'ALEX FERNANDO SAMUEL',
    userId: '00070',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00070',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00070' },
    { fullName: 'WILLYSON MANTEIGAS RENATO',
    userId: '00071',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00071',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00071' },
    { fullName: 'AVILA TONY',
    userId: '00072',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00072',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00072' },
    { fullName: 'ALEX DEYVID',
    userId: '00073',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00073',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00073' },
    { fullName: 'BOTELHO APOLIDORIO',
    userId: '00074',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00074',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00074' },
    { fullName: 'JOSE JUNIOR LEANDRO',
    userId: '00075',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00075',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00075' },
    { fullName: 'HENRIQUE RENATO',
    userId: '00076',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00076',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00076' },
    { fullName: 'BRUNO DE FERREIRA',
    userId: '00077',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00077',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00077' },
    { fullName: 'WALLACE DE MAZZINI IRVING',
    userId: '00078',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00078',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00078' },
    { fullName: 'BRASIL GIULIANI HENRIQUE PAULA',
    userId: '00079',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00079',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00079' },
    { fullName: 'SANTANA RIBEIRO',
    userId: '00080',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00080',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00080' },
    { fullName: 'CARVALHO RODRIGO',
    userId: '00081',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00081',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00081' },
    { fullName: 'MIGUEIS TORRES',
    userId: '00082',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00082',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00082' },
    { fullName: 'FRANCISCO MELLO DAMASCENO',
    userId: '00083',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00083',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00083' },
    { fullName: 'SANTOS VILAR',
    userId: '00084',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00084',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00084' },
    { fullName: 'LINO TONY DONIZETI CARVALHO',
    userId: '00085',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00085',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00085' },
    { fullName: 'ARLETE LEANDRO GODOI',
    userId: '00086',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00086',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00086' },
    { fullName: 'GODOI SALVARANI',
    userId: '00087',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00087',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00087' },
    { fullName: 'LUCIANO CARVALHO',
    userId: '00088',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00088',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00088' },
    { fullName: 'GUILHERME TONELI',
    userId: '00089',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00089',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00089' },
    { fullName: 'DANILO BARBOSA TERTO',
    userId: '00090',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00090',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00090' },
    { fullName: 'PEDROSO ALMEIDA',
    userId: '00091',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00091',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00091' },
    { fullName: 'TONY MARCO TERTO',
    userId: '00092',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00092',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00092' },
    { fullName: 'NOBRE CUNHA OLIVEIRA',
    userId: '00093',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00093',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00093' },
    { fullName: 'SANTOS SANTIAGO',
    userId: '00094',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00094',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00094' },
    { fullName: 'BAPTISTA SANTOS',
    userId: '00095',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00095',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00095' },
    { fullName: 'POLICASTRO PIRIZ',
    userId: '00096',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00096',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00096' },
    { fullName: 'DANIEL GOBI',
    userId: '00097',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00097',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00097' },
    { fullName: 'ARGEU ARLETE',
    userId: '00098',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00098',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00098' },
    { fullName: 'MARTINS PIRIZ MAURO',
    userId: '00099',
    cnhPictureUrl: 'https://image-service.moobie.com.br/api/v1/images/cnhPicture-00099',
    profilePictureUrl: 'https://image-service.moobie.com.br/api/v1/images/profilePicture-00099' } 
]

Users.forEach(publishNewUser)